include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/models/**   # Amplify codegen 산출물 린트 제외

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
